### ISSUE TITLE
I need use url  logo in footers website

### ISSUE THREAD

**Issue by msadeqi** [BePsvPT/secure-headers#29]
Hi
I need use url  logo in footers website :

https://logo.samandehi.ir/logo.aspx?id=125527&p=nbpdodrfujynujynodrfyndt
https://trustseal.enamad.ir/logo.aspx?id=85695&amp;p=6hcAP0z1rV586Pk9

it is not show 
What am i doing wrong?
Thanks

**Comment by msadeqi** [comment]
Hi, thanks 
this site https://nasimshow.ir/  
![untitled-1](https://user-images.githubusercontent.com/24833578/44778954-7c5fde80-ab93-11e8-9552-31d6bfa7f124.jpg)

thanks

**Comment by JohanMa4** [comment]
Hi, checking this url: https://logo.samandehi.ir/logo.aspx?id=125527&p=nbpdodrfujynujynodrfyndt, it doesn't return and image, instead return and html with a hidden form if you check the page code, are your sure that link is an image?

And this one: https://trustseal.enamad.ir/logo.aspx?id=85695&amp;p=6hcAP0z1rV586Pk9, return a white dot in a black screen.

I think your issue is about files or url permissions from samandehi.ir

**Comment by msadeqi** [comment]
Hi,Site permissions are correct. when
\ Bepsvpt \ SecureHeaders \ SecureHeadersMiddleware :: class,
  Disabled on the site. Logos are displayed
look at  the pic attach and site adress
![untitled-2](https://user-images.githubusercontent.com/24833578/44780129-7c151280-ab96-11e8-8d82-4cf3d42052f6.jpg)

**Comment by BePsvPT** [comment]
Hi @msadeqi,

Can you provide your csp `img-src` directive config?

**Comment by msadeqi** [comment]
'img-src' => [
            'schemes' => [
                'data:',
                'https:',
            ],
            'self' => true,
            'data' => true,
        ],

**Comment by BePsvPT** [comment]
Hi @msadeqi,

Thanks for providing this information.

Your website response header shows that the csp header is
`https://logo.samandehi.ir/logo.aspx?id=125527&p=nbpdodrfujynujynodrfyndt,https://logo.samandehi.ir/Verify.aspx?id=125527&p=rfthuiwkdshwdshwuiwkjyoe,https://trustseal.enamad.ir/logo.aspx?id=85695&amp;p=6hcAP0z1rV586Pk9,https://trustseal.enamad.ir/Verify.aspx?id=85695&amp;p=6hcAP0z1rV586Pk9&quot 'self'`

This may due to wrong configuration. Can you provide the full csp config?

**Comment by JohanMa4** [comment]
Hi @BePsvPT, checking again the website of @msadeqi https://nasimshow.ir/, it seems that the issue is fixed.

The logos are appearing, so i think that @msadeqi fixed the issue.

**Comment by BePsvPT** [comment]
Hi @JohanMa4,

Thanks for notifying me. 👍 

Hi @msadeqi,

If you have any other questions, feel free to open a new issue.
